name: nameless
description: A sample command-line application with basic argument parsing.
version: 1.0.0
license: MIT
repository: https://github.com/staylorx/dart_nameless
executables:
  nameless: bin/nameless.dart

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  analyzer: ">=8.0.0 <11.0.0"
  yaml: ^3.1.3
  json2yaml: ^3.0.0
  equatable: ^2.0.5
  fpdart: ^1.2.0
  glob: ^2.1.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  mocktail: ^1.0.3
  shouldly: ^0.5.0+1
